"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment-driven configuration.
#
# Deployment-specific values come from environment variables. The defaults make a fresh
# checkout work locally (runserver + the Next.js dev server) with no setup at all:
#
#   DJANGO_DEBUG          true/false (default: true)
#   DJANGO_SECRET_KEY     required when DJANGO_DEBUG is false
#   DJANGO_ALLOWED_HOSTS  comma-separated host names (default: localhost,127.0.0.1,[::1])
#   CORS_ALLOWED_ORIGINS  comma-separated browser origins allowed to call /api/
#                         (default: http://localhost:3000,http://127.0.0.1:3000)
#
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
_TRUE_VALUES = {'1', 'true', 'yes', 'on'}
_FALSE_VALUES = {'0', 'false', 'no', 'off'}


# Reads a boolean variable. An unrecognised value raises instead of silently meaning
# "false", so a typo such as DJANGO_DEBUG=flase fails at startup.
def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name, '').strip()
    if not raw:
        return default
    if raw.lower() in _TRUE_VALUES:
        return True
    if raw.lower() in _FALSE_VALUES:
        return False
    allowed = ', '.join(sorted(_TRUE_VALUES | _FALSE_VALUES))
    raise ImproperlyConfigured(f'{name} must be one of: {allowed} (got {raw!r}).')


# Reads a comma-separated list, trimming whitespace and dropping empty items. A variable
# that is set but empty means "no items"; an unset variable falls back to the default.
def _env_list(name: str, default: str) -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback is the key generated by startproject. It is committed to the repository and
# therefore public, so it is only accepted while DEBUG is on.
_INSECURE_DEV_SECRET_KEY = 'django-insecure--i^5bam1xi!k^$hyanp@-1kgey0aciz8=i55n@-pn5^!9jl8_c'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or _INSECURE_DEV_SECRET_KEY
if not DEBUG and SECRET_KEY == _INSECURE_DEV_SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.')

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1,[::1]')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'submissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # Adds an ETag to GET/HEAD responses and answers a matching If-None-Match with an empty
    # 304 Not Modified. It sits below CorsMiddleware so a 304 still gets its CORS headers on
    # the way out (response middleware runs bottom-up).
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework defaults shared by every API view:
# - List endpoints are paginated by server.pagination.StandardPageNumberPagination: 10 per
#   page via ?page=N (or ?pageSize=N, up to 100), returning {count, next, previous, results}
#   (mirrored by PaginatedResponse<T> in frontend/lib/types.ts).
# - django-filter is the default filter backend, so a view only needs a `filterset_class`.
# - The API is public and read-only for this challenge. That is declared explicitly (no
#   authentication classes, AllowAny), so adding auth later means changing these two
#   defaults, not every view. The admin keeps its own Django session login.
# - JSON is converted between Python snake_case and JavaScript camelCase on the way out
#   (renderer) and on the way in (parsers), so the frontend never sees snake_case keys.
#   The browsable HTML API is only offered while DEBUG is on.
# - drf-spectacular generates the OpenAPI schema from the views, serializers and filters.
_RENDERER_CLASSES = ['djangorestframework_camel_case.render.CamelCaseJSONRenderer']
if DEBUG:
    _RENDERER_CLASSES.append('rest_framework.renderers.BrowsableAPIRenderer')

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'server.pagination.StandardPageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': _RENDERER_CLASSES,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PARSER_CLASSES': [
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
    ],
}

# Options for the camelCase -> snake_case conversion of incoming data
# (e.g. "address1" stays "address1" instead of becoming "address_1").
JSON_UNDERSCOREIZE = {
    'no_underscore_before_number': True,
}

# OpenAPI schema (served at /api/schema/, browsable with Swagger UI at /api/docs/).
# The camelize hook rewrites serializer field names the way CamelCaseJSONRenderer does, so
# the schema describes the JSON the API actually returns (documentCount, not document_count).
SPECTACULAR_SETTINGS = {
    'TITLE': 'Submission Tracker API',
    'DESCRIPTION': (
        'Read-only API for reviewing broker-submitted opportunities: a filterable, paginated '
        'list of submissions, the full record of one submission, and the broker options for '
        'the list filter. JSON keys and query params are camelCase.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields',
    ],
}

# Browser origins allowed to call the API (the Next.js dev server by default). Any other
# origin gets no Access-Control-Allow-Origin header, so browsers block it from reading
# responses. CORS headers are only added under /api/; the admin never needs them.
CORS_ALLOWED_ORIGINS = _env_list(
    'CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000'
)
CORS_URLS_REGEX = r'^/api/.*$'

# Session and CSRF cookies (used by the admin) are only sent over HTTPS outside development.
# HTTPS redirects and HSTS are left to the deployment's proxy or load balancer.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
